### ISSUE TITLE
Determine how many bytes readAll() has read

### ISSUE THREAD

**Issue by danvk** [jDataView/jBinary#38]
Unlike `.read()`, `.readAll()` does not advance your current position in the file. So if you want to read a sequence of TypeSets, there's no hope.

One way would be to make the top-level type in my TypeSet an array, but I'd prefer not to do this as I may be able to avoid reading a large chunk of my buffer (i.e. I want to early out).

**Comment by RReverser** [comment]
`readAll()` is just a helper for reading entire underlying structure (from 0 offset to the very end) as type aliased by `jBinary.all`. In es6 branch, I've added 'iterator' type but it's not merged yet because it slows down things as of now.

However, you can still read items one-by-one on your own if you need it - just do a loop with `.read('YourType')` in the body.

**Comment by danvk** [comment]
Is there a way to convert a TypeSet to a Type? TypeSets can do a few things that mere Types cannot, e.g. reference one another and set endian-ness.

**Comment by RReverser** [comment]
TypeSet is just a set of types that applies to entire jBinary instance. You definitely can use custom endianness on case-by-case basis, as well as reference types from each other.

**Comment by danvk** [comment]
I see, so if I do `jBinary.read('mytype')`, and `'mytype'` is in the TypeSet that the `jBinary` object was constructed with, it'll work?

**Comment by RReverser** [comment]
Yep, exactly. As you can see from https://github.com/jDataView/jBinary/blob/master/src/proto/props.js#L61, .readAll() does pretty much the same under the hood.

**Comment by danvk** [comment]
Got it!

Thanks for the great library, btw. It's made parsing [bioinformatics formats][1] a breeze.

[1]: http://genome-source.cse.ucsc.edu/gitweb/?p=kent.git;a=blob;f=src/inc/bbiFile.h;h=e5820388ba2d83a3a891f4f766b808530729fa66;hb=HEAD

**Comment by RReverser** [comment]
Glad it worked for you well! :)
