### ISSUE TITLE
BROWSER and NODE variables

### ISSUE THREAD

**Issue by fluffynukeit** [jDataView/jBinary#42]
I hope this is an easy question to answer.  Where do the BROWSER and NODE variables get set and how do I change them?  I am compiling with browserify but it keeps including NODE code and excluding BROWSER code, which is the opposite of what I want.  When I try to load a user-selected file in the browser, I get that the type is unsupported because File objects aren't handled in the NODE code (from load.js).  I'm sure it's an easy question to answer but the parameters of the question make searching for it online very difficult.

**Comment by RReverser** [comment]
Those are compile-time constants; you're not supposed to build jBinary on your own with browserify, as build step is somewhat more complex; instead, you should use `dist/browser/jbinary.js` or https://jdataview.github.io/dist/jbinary.js.
