### ISSUE TITLE
loadData problem with ReadableStream

### ISSUE THREAD

**Issue by strobejb** [jDataView/jBinary#46]
Slightly odd bug to report that might be me simply misusing this (great!) library. In nodejs 0.10.33 everything works great, but in the latest nodejs (0.12.4) I am seeing an error when using jBinary.loadData in conjunction with a ReadableStream 

```
buffer.js:201
  length += list[i].length;
                   ^
TypeError: Cannot read property 'length' of null
    at Function.Buffer.concat (buffer.js:201:24)
    at PassThrough.<anonymous> (.....\node_modules\jbinary\dist\node\jbinary.js:451:39)
    at PassThrough.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

I'm using nodejs v0.12.4 and the 'async' library. Here is the offending code:

```
async.waterfall([
     var stream = require('fs').createReadStream('path/to/file');
     next(null, stream);
},
function parseFile(stream, next) {
  jBinary.loadData(stream, MY_TYPESET_HERE, function(err, binary) {
      // execution does not get this far
      var myData = jbinary.readAll();
  });
},
```

jBinary.loadData basically blows up when I pass a readableStream to it. I'm very new to nodejs so I'm not sure what the issue is, but presumably nodejs' ReadableStream has changed from node 0.10.x -> 0.12.x and maybe jBinary does not officially support ReadableStream as a data source?  Is this even an issue in jBinary to start with?

This code fragment is actually part of a much larger project that uses AWS's S3 storage API. I'm retrieving the file from an S3 bucket and not simply using a static file. I can work around this issue by either downloading the file to temp storage and then loading it that way (and avoiding use of ReadbleStream), or avoiding storing the S3 file to disk entirely, and keeping everything in-memory Buffer. 

As an aside, what is jBinary's preferred approach to data sources? When loading a file from disk does it load it all into memory anyway, or does it read the file chunk-by-chunk? If the file is always loaded into ram then I guess I can just use Buffers and be done with it

cheers & thanks for a really nice library

**Comment by RReverser** [comment]
As you can see from [docs](https://github.com/jDataView/jBinary/wiki/Loading-and-saving-data), `loadData` doesn't accept typesets at all (I should probably even remove it from docs as it's mostly used internally and just adds confusion). Use `jBinary.load` instead and let me know if it works.

> When loading a file from disk does it load it all into memory anyway, or does it read the file chunk-by-chunk?

Unfortunately, it loads entire file into memory since jBinary supports using offsets read directly from file (i.e. for dynamic arrays) and thus needs to have entire blob in order to perform parsing.

**Comment by strobejb** [comment]
I just saw your comment: my apologies, I have been using `jBinary.load' function as you suggest.

I have identified what is causing the problem. The problem occurs on line#449 in the `source.on("readable")` callback. This function appears to load the readableStream in chunks, and appends each chunk of data to an array. The last time `this.read()` is called it returns `null` (presumably when it reaches the end of the stream). This has a cascading effect because the subsequent call to `Buffer.concat(buffers)` fails, because the last entry in the `buffers` array is null.

    jBinary.loadData = promising(function(source, callback) {
        var dataParts;
        if (is(source, ReadableStream)) {
            var buffers = [];
            source.on("readable", function() {
                buffers.push(this.read());    /* <------ this.read() is returning null */
            }).on("end", function() {
                callback(null, Buffer.concat(buffers));
            }).on("error", callback);

Perhaps a simple check to make sure `this.read()` returns a sensible value would be a reasonable fix? I don't know enough about nodejs to judge whether the 'null' data should be handled in a different way

            source.on("readable", function() {
                var buf = this.read();
                if(buf) 
                   buffers.push(this.read());
            }).

**Comment by RReverser** [comment]
This is pretty weird given that stream should not emit `readable` when it's done and emit `end` instead.

Care to send PR with corresponding test?

**Comment by strobejb** [comment]
Yes its strange that a null buffer is being returned. I just submitted a PR & test. I'm pretty new to nodejs & the grunt workflow so you'll probably want to double-check the fix doesn't break anything inadvertently :)

**Comment by juvyc** [comment]
Any fixes on this? :-(

**Comment by krisztianb** [comment]
I'm still running into this same problem using node.js 14.16.1. 😢

**Comment by RReverser** [comment]
> 
> 
> I'm still running into this same problem using node.js 14.16.1. 😢 Wasn't this fixed by a PR from @strobejb six years ago?

Hm, I'd think so too. Although it looks like I might not have done an npm release after that...

**Comment by RReverser** [comment]
Looks like a lot of dev-dependencies got outdated and things broke :( Unfortunately, as you could have noticed, I haven't been lately able to give this project the love it deserves, but if someone is interested to step up, I'd be happy to give maintainer access.

**Comment by krisztianb** [comment]
Could you create a new release please?

I'm currently working on updating the TypeScript type definitions of this package. While doing so I noticed this bug as you can see here: https://github.com/krisztianb/DefinitelyTyped/blob/jbinary-update/types/jbinary/jbinary-tests.ts#L18

**Comment by krisztianb** [comment]
> Looks like a lot of dev-dependencies got outdated and things broke :(

Do you mean that the tests are failing?

**Comment by RReverser** [comment]
> Do you mean that the tests are failing?

No, the autorelease was setup via Travis - basically it published releases whenever a new version was tagged, but 1) that doesn't work anymore and 2) local builds fail for some obscure reasons I don't have time to debug either.

If you can get builds working again in a PR, I'm happy to publish a release manually.

**Comment by krisztianb** [comment]
I created a separate issue for the build problem here: #67 Maybe you can help me out if you find some time?
