### ISSUE TITLE
how to increase buffer size?

### ISSUE THREAD

**Issue by egoroof** [jDataView/jBinary#48]
Hello! Can you help me, please?

I want to add some additional data to file from external source. I load file with `jBinary.load` method. Then how can I add some addition bytes to it?

I tried to create a new buffer with `binary.view.byteLength + nededSize` size. Then I iterate through `binary.view.buffer` and copy it's bytes. But I found that it is empty structure.

Also I tried this:
```js
var newBinary = new jBinary(binary.view.byteLength + 128);
    for (var i = 0; i < binary.view.byteLength; i++) {
        newBinary.write('uint8', binary.read('uint8'));
    }
}
```
It's really terrible for browser

So is it possible to change buffer size?

**Comment by RReverser** [comment]
Memory is statically allocated, so you can't change buffer size of existing instance. However, you can create new instance and copy data efficiently by using `binary` type (it's listed in [docs](https://github.com/jDataView/jBinary/wiki/Standard-types#binary-types)):

```javascript
var newBinary = new jBinary(binary.view.byteLength + 128);
newBinary.write('binary', oldBinary);
```

**Comment by egoroof** [comment]
Omg. That's awesome! Thank for this lib!
