### ISSUE TITLE
Accessing contents of GZip file

### ISSUE THREAD

**Issue by jetsnguns** [jDataView/jBinary#50]
My use case is pretty simple: I have a single large csv file gzipped and I need to access it's contents as a string.
So far I understand that I need to start with:
````javascript
jBinary.load(zipfile, GZIP).then(function (jb) {
    var data = jb.readAll();
    console.log(data);
    // future code for parsing csv
    console.log('Unzipping finished');
});
````
I'm stuck after that: what object is in data now? hot do I access the actual compressed data of the archive?

**Comment by RReverser** [comment]
Can you show what you are getting when logging `data`? And which typeset where you using - this one https://github.com/jDataView/jBinary.Repo/blob/gh-pages/typeSets/gzip.js?

**Comment by jetsnguns** [comment]
Yes, here it is:
````javascript
Unzipping started
Object {_id1: 31, _id2: 139, compression: "Deflate", _reserved: 0, _hasComment: 0…}_hasComment: 0_hasExtra: 0_hasHeaderCRC: 0_hasName: 1_id1: 31_id2: 139_reserved: 0compression: "Deflate"content: (b)crc32: 1309749442extraFlags: 0input_size: 287isText: 0mod_time: Sat Feb 13 2016 03:16:11 GMT+0300 (Russia TZ 2 Standard Time)name: "dWA-compact-1.csvx"os: "FAT"__proto__: Object
Unzipping finished
````
The file name of the archived file is correct.
I am using gzip.js with a slight modification to get rid of require.js. I use raw sources of inflate/deflate with it.

**Comment by RReverser** [comment]
So yeah, as you can see from [structure in that file](https://github.com/jDataView/jBinary.Repo/blob/gh-pages/typeSets/gzip.js#L102), it should be in `content` property, except that decompression happens lazily for performance reason (so you need to call `.content()` to actually decompress data).

**Comment by jetsnguns** [comment]
Yes, I tried that and it is not working - I receive an object instead of a string:
````javascript
jBinary.load(zipfile, GZIP).then(function (jb) {

    var data = jb.readAll();

    var c = data.content();

    console.log(c);

    console.log('Unzipping finished');
});
````

````javascript
Unzipping started
h {view: e, contexts: Array[0], typeSet: Object, cacheKey: "jBinary.Cache.3"}cacheKey: "jBinary.Cache.3"contexts: Array[0]typeSet: Objectview: e__proto__: h
Unzipping finished
````

**Comment by jetsnguns** [comment]
I have finally figured it out: need to call .content().read('string').

**Comment by RReverser** [comment]
@jetsnguns Yeah, sorry for not clarifying - it returns another jBinary into decompressed data to give you ability to work with it as regular file.
