### ISSUE TITLE
Dispatch to typedef based on context?

### ISSUE THREAD

**Issue by sch** [jDataView/jBinary#54]
Is there a way to dispatch based on context? Say I have:

``` js
var typedef = {
  Message: {
    header: "Header",
    payload: "Shape",
  },

  Header: {
    category: [ "enum", "uint8", [ "Shape", "Meal" ]],
    id: "uint8"
  },

  Shape: {
    color: "uint8",
    shape: [ "enum", "uint8", [ "circle", "square" ]]
  },

  Meal: {
    name: [ "string", 20 ],
    prepTime: "uint8"
  }
}

new Binary(arrayBuffer, typedef).read("Message")
// => {
//   header: {
//     category: "Shape"
//     id: 209,
//   },
//   payload: {
//     color: 13,
//     shape: "square",
//   }
// }
```

Here, I've hard-coded the payload type to "Shape", but could I get this value based on the context parsed so far? Something along the lines of:

``` js
var typedef = {
  Message: {
    header: "Header",
    payload: function (context) {
      return context.header.category
    }
  },

  Header: {
    category: [ "enum", "uint8", [ "Shape", "Meal" ]],
    id: "uint8"
  },

  Shape: {
    color: "uint8",
    shape: [ "enum", "uint8", [ "circle", "square" ]]
  },

  Meal: {
    name: [ "string", 20 ],
    prepTime: "uint8"
  }
}
```

I know there are other ways of accomplishing this (splitting my calling code into two parts (parsing the header, then parsing the payload), writing one huge typeset and my own reading/writing methods), but I wanted to ask if there was an idiomatic way of doing this. Happy to add an example to the docs if there is, happy to write a type if there isn't.

**Comment by freehuntx** [comment]
You can do pretty much everything with ifs.

```
var typedef = {
  Message: {
    header: "Header",
    payload: ['if', function(ctx) { ctx.header.category == 0; }, 'Shape', 'Meal']
  },

  Header: {
    category: [ "enum", "uint8", [ "Shape", "Meal" ]],
    id: "uint8"
  },

  Shape: {
    color: "uint8",
    shape: [ "enum", "uint8", [ "circle", "square" ]]
  },

  Meal: {
    name: [ "string", 20 ],
    prepTime: "uint8"
  }
}
```

**Comment by sch** [comment]
@freehuntx — I'm [not sure](http://requirebin.com/?gist=d195a3567ba822365f5d049130cd2e83) that works. `category` at that point in the program has already been parsed into the `"Meal"` enum value. I just can't use that value to dispatch to the `Meal` typedef I've described.

I have been getting around this by using a `Template` [defined inline](http://requirebin.com/?gist=d195a3567ba822365f5d049130cd2e83):

```js
var typeDef = {
  Message: {
    header: 'Header',
    payload: Binary.Template({
      setParams: function () {
        this.getBaseType = function (context) {
          return context.header.category;
        }
      }
    })
  }
  // ...
}
```

But I find this extremely clunky. In reality, I'm parsing an enormous, cursed Bluetooth protocol, so the message header is actually something more along the lines of 
`<<Type:8, MinPayloadSize:8, MessageClass:8, MessageMethod:8, Payload/binary>>`.

Coming up with an elegant way of dispatching to the correct payload definition based on a combination of `Type`, `MessageClass`, and `MessageMethod` is escaping me right now.

**Comment by RReverser** [comment]
@sch Need to dig deeper into your problem but at least one thing you can do is avoid `setParams` and instead define `getBaseType` directly on `Template`:

```javascript
  Message: {
    header: 'Header',
    payload: Binary.Template({
      getBaseType: context => context.header.category
    })
  },
```
