### ISSUE TITLE
Type Caching and Memory Use

### ISSUE THREAD

**Issue by lukelaws** [jDataView/jBinary#56]
I am using jBinary to construct pdus for a networking application.  I send out many requests and my memory usage is climbing over time.  It appears that this is a result of the typeset being cached each time i call jBinary.  I'm having trouble locating in the source exactly where the references to types are being stored... privately in the module it seems.  

It's pretty easy to reconstruct:

```
for (var i = 0; i < 1000000; i++) {
  jBinary(new Buffer(200), {test: 'int32'});
};
```
This results in memory that does not get GCd.
Is there a way of disabling the typeset caching?

Or maybe i'm fooling myself altogether here, i can't find where the typesets are referenced in the module, I'm not sure why they are not released.  I will keep reading the source in the meantime.

**Comment by lukelaws** [comment]
Sorry, this was an issue with my environment.  My mistake, thanks for jBinary btw, excellent project.

**Comment by RReverser** [comment]
Thanks :) Glad you figured what was going on.

**Comment by likev** [comment]
> 
> 
> Sorry, this was an issue with my environment. My mistake, thanks for jBinary btw, excellent project.

I have the same problem, can you tell me how to fix it?
