### ISSUE TITLE
Question: How to convert the "uint16" value to half-precision float (i.e. "float16")?

### ISSUE THREAD

**Issue by stuartZhang** [jDataView/jBinary#57]
Hello,

In my project, I need to unpack a binary file where there are a few of the half-precision float (i.e. "float16") values. As of this writing, I read it from the binary stream by using the specification API "this.binary.read('uint16')".

Could you please teach me how to convert the "uint16" number back to the "float16" using JavaScript?

**Comment by RReverser** [comment]
Not sure to be honest, but feel free to send PR if you find a way.
