### ISSUE TITLE
Dynamic Types?

### ISSUE THREAD

**Issue by freezy** [jDataView/jBinary#58]
My blob starts with a `string0` followed by an object whose structure is dependent on this previously read `string0`. So I figured something like this:

```javascript
var typeSet = {
	Data: {
		name: 'string0',
		data: [ 'object', function(context) {
			return context.name;
		}]
	},
	Dimensions: {
		width: 'int32',
		height: 'int32'
	}
};
```
For example if the `string0` was "Dimensions", `Data.data` would become an object of type Dimensions. I've spent hours reading through the Wiki and getting a grasp on how jBinary works. I've also tried changing the [jBinary.Type example](https://github.com/jDataView/jBinary/wiki/jBinary.Type) from `array` to `object` without success.

Any help or suggestions would be appreciated.

**Comment by RReverser** [comment]
Duplicate of https://github.com/jDataView/jBinary/issues/54? At least sounds like a very similar question.

**Comment by freezy** [comment]
You're right, and that actually works.

For reference:

```javascript
var typeSet = {
	Data: {
		name: 'string0',
		data: jBinary.Template({
			getBaseType: function(context) {
				return context.name;
			}
		})
	},
	Dimensions: {
		width: 'int32',
		height: 'int32'
	}
};
```

Cheers!
