### ISSUE TITLE
jBinary::readAll does not mutate the internal pointer

### ISSUE THREAD

**Issue by Phrohdoh** [jDataView/jBinary#59]
Given:

```javascript
let typeSet = {
    'jBinary.all': 'myAll',
    myAll: ['string0', 30],
};

let filePathToLoad = proc.argv[1];

jBinary.load(filePathToLoad, typeSet).then(bin => {
    bin.readAll();
    console.log(bin.tell());
}).catch((err) => {
    console.info(err);
});
```

If you do `bin.read('myAll'); console.log(bin.tell());` the result will be `30` as is expected.

But `bin.readAll();` _does not_ yield a position of `30`, it gives you back `0`.

This can also be observed if `myAll` is, for example, changed to `'uint8'` or `['array', 'uint8', N]`.

---

I believe this should be noted in the documentation (if I missed this please correct me and close this).

This makes sense, if done intentionally, so that data may be read, mutated, then written back to the data source.

**Comment by RReverser** [comment]
Hm, I'm not sure I follow. Looks like internal pointer was properly updated from 10 to 35 during `str25` call?

**Comment by Phrohdoh** [comment]
Ok so I've discovered the real issue here is `readAll` (or perhaps how I am using it).
I'll update the OP.

**Comment by RReverser** [comment]
Yes, `readAll` is designed to be used as an immutable function that you can call whenever without changing your state.
