### ISSUE TITLE
writeAll() method documentation and functionality

### ISSUE THREAD

**Issue by kpetrow** [jDataView/jBinary#60]
Hi,
Reading through the API it seems the writeAll method is a little short on documentation and I had a couple question.  I am writing a header of various typed values(couple hundred bytes) then a large float32 array(3-100MB).  Currently I'm using <loop float32>bin.write('float32',array[counter])</loop>. I am experiencing slow performance.

1.  writeAll(data) doesn't seem to work for writeAll(float32array).  Do i need to convert this to arrayBuffer first?  Seems like i do since it takes jBinary.all': 'float32' in typeset object.
2.  Does writeAll start at the bin.tel(() position?  Or is always starting at 0 offset?
3.  Do i need shove everything, header too, into a arrayBuffer, then some type of typeset mapping, then writeAll()?

Thanks,
Karl

**Comment by RReverser** [comment]
`writeAll` is nothing more than a wrapper around `write` with predefined name (`jBinary.all`) and without advancing position. You won't get any performance improvements from using it over `write`.

**Comment by kpetrow** [comment]
Yeah, dove into the code a little bit and saw that. 

`proto.writeAll = function(data) { return this.write("jBinary.all", data, 0);}`

 Is there a faster way to append an float32array?  Maybe just using fs?  Or create arrayBuffer with entire file?

**Comment by kpetrow** [comment]
just append it using fs.  Super fast:

`fs.appendFileSync(Name, new Buffer(Array.buffer))`
