### ISSUE TITLE
How to read a string

### ISSUE THREAD

**Issue by Crauzer** [jDataView/jBinary#71]
How am I supposed to read a string with this library ?

These are the parameters for the `read` method:
![image](https://user-images.githubusercontent.com/18646077/117362915-269f7080-aebc-11eb-9fd2-69473c058cf5.png)

I don't see a way to specify the `length` parameter anywhere

**Comment by RReverser** [comment]
Did you check the API docs linked in README? https://github.com/jDataView/jBinary/wiki

**Comment by RReverser** [comment]
I'll close this as this is documented under Strings in the docs.

**Comment by Crauzer** [comment]
I read every single page of the docs in the wiki and I honestly still have no idea how your library works.

After hours of debugging and looking at the source I still cannot figure out how to read a string, or rather how to provide a length parameter to the `read` function as shown above.

The `read` function only accepts a type name and an offset, no mention of params for the provided type.

**Comment by Crauzer** [comment]
I'm also using TypeScript by the way, so your type definitions might be incorrect ? Since there is aboslutely no way to specify params in the `read` function for a given `type`

**Comment by RReverser** [comment]
> I read every single page of the docs in the wiki and I honestly still have no idea how your library works.

https://github.com/jDataView/jBinary/wiki/Type-usage-syntax describes how to pass type params in general (`['typeName', arg1, arg2, ..., argN]`).
https://github.com/jDataView/jBinary/wiki/Standard-types#strings documents string type arguments to be passed using syntax above.
https://github.com/jDataView/jBinary/wiki/Typesets even has a detailed example, showing usage of strings among others.

**Comment by Crauzer** [comment]
I'm sorry but your docs honestly make no sense and don't match your type definitions, if you look at the first comment I made it shows the method signature in TypeScript for the `read` method.

It only accepts 2 arguments, `type` and `offset`, `type` can either be a `string` or a `[string, string, number?]` which does definitely not match anything in your docs. So I'm lost as to how I'm supposed to pass parameters into this function in a sane way.

**Comment by Crauzer** [comment]
It just seems like the function signature is missing a `params: any[]` argument

**Comment by RReverser** [comment]
I don't know where TS definitions you're seeing are coming from, and correspondingly can't comment on why they don't match the docs - the library itself doesn't have TS definitions.

But I've provided plenty of links above with examples, including specific example for strings:

> jDataView/jBinary/wiki/Typesets even has a detailed example, showing usage of strings among others.

That page literally shows `['string0', 256]` as an example of passing length.
